* <<<405>>> DATABASE MANAGEMENT SYSTEMS
:properties:
:author: Mr. B. Senthil Kumar and Dr. P. Mirunalini
:date: 
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** Course Objectives
- To introduce the fundamentals of Database systems and Conceptual Modeling .
- To learn SQL and relational model.
- To study relational database design.
- To understand the storage structures, indexing techniques and Query processing techniques .
- To explore the fundamental concepts of transaction processing, concurrency control and recovery techniques.


{{{unit}}}
|Unit I | <Title> | <Hours> |
|Unit I | <Database Concepts and Conceptual Modeling> | <9> |
Characteristics of database -- Database users -- Data models -- Schemas: Three-schema architecture; Database system environment -- Centralized and client/server DBMS architectures -- Data modeling using ER model -- Enhanced-ER model.

{{{unit}}}
|Unit II | <Title> | <Hours> |

{{{unit}}}
|Unit III | <Title> | <Hours> |

{{{unit}}}
|Unit IV | <Title> | <Hours> |

{{{unit}}}
|Unit V | <Title> | <Hours> |


\hfill *Total: <Total Hours>*

** Course Outcomes
After the completion of this course, students will be able to: 
- Understand the basic concepts of machine learning (K2).
- second
      
** References
1. Stephen Marsland, ``Machine Learning – An Algorithmic Perspective'', Second Edition, Chapman and Hall/CRC Machine Learning and Pattern Recognition Series, 2014.
