* <<<405>>> DATABASE MANAGEMENT SYSTEMS
:properties:
:author: Mr. B. Senthil Kumar and Dr. P. Mirunalini
:date: 
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** Course Objectives
- To introduce the fundamentals of Database Management Systems, data models and to represent a database system using ER diagrams.
- To learn SQL and relational model.
- To study relational database design.
- To understand the internal storage structures using different file and indexing techniques and Query processing techniques .
- To explore the fundamental concepts of transaction processing- concurrency control techniques and recovery procedures.

{{{unit}}}
|Unit I | <Title> | <Hours> |


{{{unit}}}
|Unit II | <Title> | <Hours> |

{{{unit}}}
|Unit III | <Title> | <Hours> |

{{{unit}}}
|Unit IV | <Title> | <Hours> |

{{{unit}}}
|Unit V | <Title> | <Hours> |


\hfill *Total: <Total Hours>*

** Course Outcomes
After the completion of this course, students will be able to: 
- Understand the basic concepts of machine learning (K2).
      
** References
1. Stephen Marsland, ``Machine Learning – An Algorithmic Perspective'', Second Edition, Chapman and Hall/CRC Machine Learning and Pattern Recognition Series, 2014.
