* <<<405>>> DATABASE MANAGEMENT SYSTEMS
:properties:
:author: Mr. B. Senthil Kumar and Dr. P. Mirunalini
:date: 
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** Course Objectives
- To introduce the fundamentals of Database systems and Conceptual Modeling .
- To learn SQL and relational model.
- To study relational database design.
- To understand the storage structures, indexing techniques and Query processing techniques .
- To explore the fundamental concepts of transaction processing, concurrency control and recovery techniques.


{{{unit}}}
|Unit I | Database Concepts and Conceptual Modeling | 9 |
Characteristics of database -- Database users -- Data models, Schemas -- Three-schema architecture -- Database system environment -- Centralized and client/server DBMS architectures -- Data modeling using ER model -- Enhanced-ER model.

{{{unit}}}
|Unit II | Relational Model and SQL | 10 |
Relational model: Concepts -- Constraints -- Update operations ; Basic SQL: Data Definition -- SQL constraints -- Basic retrieval queries -- Insert, delete and update commands ; More SQL: Complex retrieval queries -- Assertions and triggers -- Views -- Schema modification ; Relational Algebra: Unary and binary relational operations -- Set theory operations -- Additional operations.

{{{unit}}}
|Unit III | Database Design | 9 |
Design guidelines -- Functional dependencies -- First, second and third Normal Forms -- Boyce-Codd Normal Forms -- MVD and 4NF -- Join dependencies and 5NF ; FD: Inference rules, minimal cover -- Relational decomposition properties -- Algorithms for relational database schema design -- ER-to-relational mapping.

{{{unit}}}
|Unit IV | Database Implementation and Query Processing | 9 |
File structure: Heap files -- Sorted files – Hashing techniques ; Indexing: single-level indexes -- multi-level indexes -- B-Trees and B+-Trees -- Indexes on multiple keys; Query processing: Strategies -- External sorting – Algorithm for SELECT and JOIN operations

{{{unit}}}
|Unit V | Transaction, Concurrency and Recovery | 9 |
Transaction Processing: Concepts -- ACID properties -- schedules -- serializability; Concurrency control: Two-phase locking technique -- Timestamp Ordering; Recovery: Concepts -- Deferred update -- Immediate update -- Shadow paging -- Multidatabase system recovery

\hfill *Total: <45>*

** Course Outcomes
After the completion of this course, students will be able to: 
- Understand the database concepts and apply ER models to any real world application - (K3)
- Write complex queries using SQL-(K3)
- Design Databases for applications using normalization and ER to Relational mapping - (K3)
- Compare and contrast various indexing strategies in different database systems-(K2)
- Apply transaction processing, concurrency control and recovery mechanisms for practical problems. (K3)
      
** Text Books 
1. Ramez Elmasri and Shamkant B. Navathe, ``Fundamentals of Database Systems'', Pearson, 7th Edition, 2016. 


** Reference Books:
1. Abraham Silberschatz, Henry F. Korth and S. Sudharshan, ``Database System Concepts'', Tata Mc Graw Hill, 6th Edition, 2011. 
2. Jeffrey D Ullman, Jennifer Widom, ``A First Course in Database Systems'', Pearson Education, 3rd Edition, 2014.
3. S.Sumathi, S. Esakkirajan, `` Fundamentals of Relational Database Management Systems '', (Studies in Computational Intelligence), Springer-Verlag, 2007.
4. Raghu Ramakrishnan, `` Database Management Systems'', Tata Mc Graw Hill, 4th Edition, 2010.
